export type StorePlan = "STARTER" | "PRO" | "ELITE";

export const STORE_PLANS = {
  STARTER: {
    key: "STARTER",
    name: "Starter",
    emoji: "",
    price: 497,
    days: 30,
    anunciosExtras: 5,
    anunciosTotal: 25,
    destaques: 2,
    features: [
      "Perfil Loja",
      "Vitrine Personalizada automática",
      "Nome da Loja + URL exclusiva",
      "+ 5 anúncios além dos 20 (25 no total)",
      "2 Destaques mensais",
      "Selo de verificação",
    ],
    notIncluded: [
      "Links de redes sociais no perfil",
      "Acesso ao e-mail e telefone do lead",
      "Analytics de anúncios",
      "Simulação de Financiamento",
      "Destaque Lojas na Home",
    ],
    socialLinks: false,
    leadContact: false,
    analytics: false,
    financiamento: false,
    homeDestaque: false,
  },
  PRO: {
    key: "PRO",
    name: "Pro",
    emoji: "",
    price: 797,
    days: 30,
    anunciosExtras: 15,
    anunciosTotal: 35,
    destaques: 5,
    features: [
      "Perfil Loja",
      "Vitrine Personalizada automática",
      "Nome da Loja + URL exclusiva",
      "+ 15 anúncios além dos 20 (35 no total)",
      "5 Destaques/Mês",
      "Selo de verificação",
      "Links de redes sociais no perfil",
      "Acesso ao e-mail e telefone do lead",
    ],
    notIncluded: [
      "Analytics de anúncios",
      "Simulação de Financiamento",
      "Destaque Lojas na Home",
    ],
    socialLinks: true,
    leadContact: true,
    analytics: false,
    financiamento: false,
    homeDestaque: false,
  },
  ELITE: {
    key: "ELITE",
    name: "Elite",
    emoji: "",
    price: 1197,
    days: 30,
    anunciosExtras: 30,
    anunciosTotal: 50,
    destaques: 10,
    features: [
      "Perfil Loja",
      "Vitrine Personalizada",
      "Nome da Loja + URL exclusiva",
      "+ 30 anúncios além dos 20 (50 no total)",
      "10 Destaques/Mês",
      "Selo de verificação",
      "Links de redes sociais no perfil",
      "Receba e-mail e telefone do lead",
      "Analytics de anúncios",
      "Simulação de Financiamento integrada",
      "Destaque Lojas na Home",
    ],
    notIncluded: [],
    socialLinks: true,
    leadContact: true,
    analytics: true,
    financiamento: true,
    homeDestaque: true,
  },
} as const;

export function getPlanLimits(plan: StorePlan | null) {
  if (!plan || !STORE_PLANS[plan]) return { anunciosTotal: 20, destaques: 0 };
  return {
    anunciosTotal: STORE_PLANS[plan].anunciosTotal,
    destaques: STORE_PLANS[plan].destaques,
  };
}
