import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#e5ff76",
        "on-primary-fixed-variant": "#665500",
        "error-dim": "#b92902",
        "on-primary": "#fff2cd",
        "on-error-container": "#520c00",
        "on-secondary-container": "#525151",
        "tertiary-fixed": "#e3fd74",
        "on-secondary": "#f5f2f1",
        "surface-container-low": "#f0f1f1",
        "primary-container": "#ffd709",
        "surface-container-highest": "#dbdddd",
        "inverse-primary": "#ffd709",
        "primary-fixed-dim": "#efc900",
        "on-background": "#2d2f2f",
        "inverse-surface": "#0c0f0f",
        "tertiary-container": "#e3fd74",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#f6f6f6",
        "outline-variant": "#acadad",
        "on-secondary-fixed": "#403f3f",
        "on-surface-variant": "#5a5c5c",
        "on-error": "#ffefec",
        "on-tertiary-fixed-variant": "#5b6b00",
        "secondary-container": "#e5e2e1",
        "secondary-fixed": "#e5e2e1",
        primary: "#6c5a00",
        "on-tertiary-fixed": "#414d00",
        "tertiary-dim": "#485500",
        "secondary-dim": "#504f4f",
        "surface-tint": "#6c5a00",
        "surface-dim": "#d3d5d5",
        "on-tertiary-container": "#516000",
        "primary-fixed": "#ffd709",
        "on-surface": "#2d2f2f",
        "primary-dim": "#5e4e00",
        "inverse-on-surface": "#9c9d9d",
        "on-primary-fixed": "#453900",
        surface: "#f6f6f6",
        "tertiary-fixed-dim": "#d5ee68",
        tertiary: "#536200",
        "on-primary-container": "#5b4b00",
        "secondary-fixed-dim": "#d6d4d3",
        "on-secondary-fixed-variant": "#5c5b5b",
        "surface-container-high": "#e1e3e3",
        "surface-variant": "#dbdddd",
        "error-container": "#f95630",
        background: "#f6f6f6",
        secondary: "#5c5b5b",
        outline: "#767777",
        error: "#b02500",
        "surface-container": "#e7e8e8",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["var(--font-barlow)", "Arial Narrow", "Arial", "sans-serif"],
        body:     ["var(--font-inter)", "system-ui", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Helvetica Neue", "Arial", "sans-serif"],
        label:    ["var(--font-inter)", "system-ui", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Helvetica Neue", "Arial", "sans-serif"],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};

export default config;
