ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "accountType" TEXT NOT NULL DEFAULT 'PF';
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "cnpj" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "companyName" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "tradeName" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "storeSlug" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "storeBannerUrl" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "storeDescription" TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS "users_cnpj_key" ON "users"("cnpj");
CREATE UNIQUE INDEX IF NOT EXISTS "users_storeSlug_key" ON "users"("storeSlug");
