/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VeiculosRouteImport } from './routes/veiculos'
import { Route as SegurosRouteImport } from './routes/seguros'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as MonetizacaoRouteImport } from './routes/monetizacao'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as FinanciamentoRouteImport } from './routes/financiamento'
import { Route as DirecaoRouteImport } from './routes/direcao'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AnunciosRouteImport } from './routes/anuncios'
import { Route as IndexRouteImport } from './routes/index'

const VeiculosRoute = VeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => rootRouteImport,
} as any)
const SegurosRoute = SegurosRouteImport.update({
  id: '/seguros',
  path: '/seguros',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const MonetizacaoRoute = MonetizacaoRouteImport.update({
  id: '/monetizacao',
  path: '/monetizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanciamentoRoute = FinanciamentoRouteImport.update({
  id: '/financiamento',
  path: '/financiamento',
  getParentRoute: () => rootRouteImport,
} as any)
const DirecaoRoute = DirecaoRouteImport.update({
  id: '/direcao',
  path: '/direcao',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AnunciosRoute = AnunciosRouteImport.update({
  id: '/anuncios',
  path: '/anuncios',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anuncios': typeof AnunciosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/direcao': typeof DirecaoRoute
  '/financiamento': typeof FinanciamentoRoute
  '/leads': typeof LeadsRoute
  '/monetizacao': typeof MonetizacaoRoute
  '/relatorios': typeof RelatoriosRoute
  '/seguros': typeof SegurosRoute
  '/veiculos': typeof VeiculosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anuncios': typeof AnunciosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/direcao': typeof DirecaoRoute
  '/financiamento': typeof FinanciamentoRoute
  '/leads': typeof LeadsRoute
  '/monetizacao': typeof MonetizacaoRoute
  '/relatorios': typeof RelatoriosRoute
  '/seguros': typeof SegurosRoute
  '/veiculos': typeof VeiculosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anuncios': typeof AnunciosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/direcao': typeof DirecaoRoute
  '/financiamento': typeof FinanciamentoRoute
  '/leads': typeof LeadsRoute
  '/monetizacao': typeof MonetizacaoRoute
  '/relatorios': typeof RelatoriosRoute
  '/seguros': typeof SegurosRoute
  '/veiculos': typeof VeiculosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anuncios'
    | '/configuracoes'
    | '/direcao'
    | '/financiamento'
    | '/leads'
    | '/monetizacao'
    | '/relatorios'
    | '/seguros'
    | '/veiculos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anuncios'
    | '/configuracoes'
    | '/direcao'
    | '/financiamento'
    | '/leads'
    | '/monetizacao'
    | '/relatorios'
    | '/seguros'
    | '/veiculos'
  id:
    | '__root__'
    | '/'
    | '/anuncios'
    | '/configuracoes'
    | '/direcao'
    | '/financiamento'
    | '/leads'
    | '/monetizacao'
    | '/relatorios'
    | '/seguros'
    | '/veiculos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnunciosRoute: typeof AnunciosRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DirecaoRoute: typeof DirecaoRoute
  FinanciamentoRoute: typeof FinanciamentoRoute
  LeadsRoute: typeof LeadsRoute
  MonetizacaoRoute: typeof MonetizacaoRoute
  RelatoriosRoute: typeof RelatoriosRoute
  SegurosRoute: typeof SegurosRoute
  VeiculosRoute: typeof VeiculosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/veiculos': {
      id: '/veiculos'
      path: '/veiculos'
      fullPath: '/veiculos'
      preLoaderRoute: typeof VeiculosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguros': {
      id: '/seguros'
      path: '/seguros'
      fullPath: '/seguros'
      preLoaderRoute: typeof SegurosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monetizacao': {
      id: '/monetizacao'
      path: '/monetizacao'
      fullPath: '/monetizacao'
      preLoaderRoute: typeof MonetizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financiamento': {
      id: '/financiamento'
      path: '/financiamento'
      fullPath: '/financiamento'
      preLoaderRoute: typeof FinanciamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/direcao': {
      id: '/direcao'
      path: '/direcao'
      fullPath: '/direcao'
      preLoaderRoute: typeof DirecaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anuncios': {
      id: '/anuncios'
      path: '/anuncios'
      fullPath: '/anuncios'
      preLoaderRoute: typeof AnunciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnunciosRoute: AnunciosRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DirecaoRoute: DirecaoRoute,
  FinanciamentoRoute: FinanciamentoRoute,
  LeadsRoute: LeadsRoute,
  MonetizacaoRoute: MonetizacaoRoute,
  RelatoriosRoute: RelatoriosRoute,
  SegurosRoute: SegurosRoute,
  VeiculosRoute: VeiculosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
